using System;using System.Collections.Generic;using System.Reflection;using System.IO;using System.Linq;using UnityEngine;using Skill;using Character;
namespace UnityEngine {
 public class Header:Attribute{public Header(string s){}}public class Min:Attribute{public Min(float x){}}public class Range:Attribute{public Range(float a,float b){}}public class CreateAssetMenu:Attribute{public string fileName,menuName;}public class ScriptableObject{}public class Sprite{}public class AnimationClip{}
 public static class JsonUtility{public static T FromJson<T>(string s)=>new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<T>(s);}
 public class Collider2D:Component{}public static class Physics2D{public static Collider2D[] Candidates=Array.Empty<Collider2D>();public static Collider2D[] OverlapCircleAll(Vector2 c,float r)=>Candidates.Where(x=>Vector2.Distance(c,x.transform.position)<=r).ToArray();}
}
namespace String {public class StringManager{public static StringManager Instance=new();public string Get(string a,string b)=>a;}}
namespace Skill {
 public class EquipmentBaseProfileSO{public float BasePriority;}public class SkillMoveSO{}public class SpawnSkillSO{}public class EquipmentUpgradeTableSO{}public class BaseVisualSO{}public class SkillAnimationVfxProfileSO{}public class SpritePresentationCalibrationProfileSO{}
}
namespace Effect{public class EffectEntrySO{}}
class CastReadback {string castId;TargetingType targetingType;float castTime,cooldown,range;bool skipAttackAnimation;Effect.EffectEntrySO[] selfEffects;public float Cooldown=>cooldown; /* CASTSETTER */ }
class SerializedObject {public EquipmentSkillSO value;public SerializedObject(EquipmentSkillSO s){value=s;}public void ApplyModifiedPropertiesWithoutUndo(){}}
class Generator {
 class ComboJson{}
 static Sprite FindSpriteById(string s)=>null;static void SetString(SerializedObject s,string n,string v)=>Set(s,n,v);static void SetObjectReference(SerializedObject s,string n,object v)=>Set(s,n,v);static void SetObjectArray(SerializedObject s,string n,object v)=>Set(s,n,v);static void Set(SerializedObject s,string n,object v)=>typeof(EquipmentSkillSO).GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).SetValue(s.value,v);static void ApplyComboProfile(SerializedObject s,ComboJson c,SkillHitSO[] h){}
 public static void Materialize(string json,EquipmentSkillSO so,SkillCastSO cast){var dto=ParseEquipmentSkillJson(json);ApplySkillFields(so,dto,new(),cast,null,new[]{new SkillHitSO()},null,null,null,null);}
 /* GENERATOR */
}
class MoveData{public Vector2 targetPosition;}
class ProjectileRuntimeData{public Vector2 spawnPosition;public MoveData moveRuntime=new();}
class ProjectileEntity{}
class ProjectileFactory {public List<ProjectileRuntimeData> Spawned=new();public ProjectileEntity SpawnOriented(ProjectileRuntimeData d){Spawned.Add(d);return new();}}
class Resolver {
 public Vector2? ExplicitPoint;public SkillAimMode? Mode;public Vector2 Direction;public GameObject Target;
 public ProjectileRuntimeData[] ResolveProjectileRuntime(EquipmentSkillRuntimeData r,GameObject caster,GameObject target,Vector2 spawn,Vector2 direction,Vector2? point,int index,AnimationClip clip,SkillAnimationVfxProfileSO visual,SpritePresentationCalibrationProfileSO calibration,string token,bool? crit,float weight,int combo,SkillHitSO hit,bool suppress,float life,SkillAimMode? mode){ExplicitPoint=point;Mode=mode;Direction=direction;Target=target;return new[]{new ProjectileRuntimeData{spawnPosition=spawn+direction*.2f}};}
}
class Helper {
 static Resolver skillResolver=new();static ProjectileFactory factory=new();static ProjectileFactory GetProjectileFactory()=>factory;static SkillCastSO ResolveCastSo(EquipmentSkillRuntimeData r)=>r.sourceEquipment.CastSo;static void ApplyCastSelfEffects(EquipmentSkillRuntimeData r,GameObject c){}
 public static (Vector2 spawn,Resolver resolver) Fire(ManualSkillAim? aim,bool legacyPoint=false){factory=new();skillResolver=new();var g=new GameObject();g.transform.position=new Vector3(5,3,0);var r=new EquipmentSkillRuntimeData();r.sourceEquipment.CastSo.Range=4;var target=aim?.Target;bool result=UseSkillProjectilesAndSelfEffects(r,g.transform,target,legacyPoint||aim?.Mode==SkillAimMode.GroundPoint,aim?.Point??new Vector2(99,99),manualAim:aim);if(!result)throw new Exception("fire failed");return(factory.Spawned[0].spawnPosition,skillResolver);}
 /* HELPER */
}
class TargetResolver {
 /* TARGET */
}
static class Tests {
 static int count;static void T(string n,Action a){a();count++;Console.WriteLine("PASS "+n);}static void C(bool b){if(!b)throw new Exception("assertion");}
 static void Main(){
 T("unknown-and-invalid-serialized-mode-fail-closed",()=>{C(SkillAimPolicy.Parse("direction")==SkillAimMode.Invalid&&SkillAimPolicy.Parse("garbage")==SkillAimMode.Invalid&&SkillAimPolicy.Resolve((SkillAimMode)99,new())==SkillAimMode.Invalid);});
 T("deterministic-legacy-cast-migration",()=>{foreach(TargetingType t in Enum.GetValues(typeof(TargetingType))){var expected=t==TargetingType.None||t==TargetingType.Self?SkillAimMode.Self:t==TargetingType.AutoTarget?SkillAimMode.Target:t==TargetingType.Position?SkillAimMode.GroundPoint:SkillAimMode.Direction;C(SkillAimPolicy.Resolve(SkillAimMode.Legacy,new SkillCastSO{TargetingType=t})==expected);}C(SkillAimPolicy.Resolve(SkillAimMode.Legacy,new SkillCastSO{SnapshotTargetPointOnCast=true})==SkillAimMode.GroundPoint);});
 T("JSON-DTO-production-materializer-SO-idempotent-twelve-slots",()=>{var rows=new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<List<Dictionary<string,object>>>(File.ReadAllText("Artifacts/Engineering/SeojinManualControl/rootfix-05/slot-manifest.json"));int n=0;foreach(var row in rows){if(!row.ContainsKey("json"))continue;string json=File.ReadAllText((string)row["json"]);var so=new EquipmentSkillSO();Generator.Materialize(json,so,new());var first=so.AimMode;Generator.Materialize(json,so,new());C(so.AimMode==first&&first==SkillAimPolicy.Parse((string)row["aimMode"]));var field=typeof(EquipmentSkillSO).GetField("aimMode",BindingFlags.NonPublic|BindingFlags.Instance);string yaml=File.ReadAllText((string)row["asset"]);C(yaml.Contains("  aimMode: "+(int)(SkillAimMode)field.GetValue(so)));C(so.AimInputSource==SkillAimPolicy.ParseInputSource((string)row["aimInputSource"]));var inputField=typeof(EquipmentSkillSO).GetField("aimInputSource",BindingFlags.NonPublic|BindingFlags.Instance);C(yaml.Contains("  aimInputSource: "+(int)(AimInputSource)inputField.GetValue(so)));n++;}C(n==12);});
 T("JSON-unknown-replaces-prior-mode-with-invalid",()=>{var so=new EquipmentSkillSO();Generator.Materialize("{\"equipmentId\":\"x\",\"aimMode\":\"Direction\"}",so,new());Generator.Materialize("{\"equipmentId\":\"x\",\"aimMode\":\"bad\"}",so,new());C(so.AimMode==SkillAimMode.Invalid);});
 T("JSON-missing-mode-legacy-repeat-preserves-cast-semantics",()=>{var so=new EquipmentSkillSO();var cast=new SkillCastSO{TargetingType=TargetingType.Self};Generator.Materialize("{\"equipmentId\":\"x\"}",so,cast);C(so.AimMode==SkillAimMode.Self);Generator.Materialize("{\"equipmentId\":\"x\"}",so,cast);C(so.AimMode==SkillAimMode.Self);});
 T("Direction-real-helper-no-ground-spawn-no-explicit-point-override",()=>{var x=Helper.Fire(new ManualSkillAim(SkillAimMode.Direction,new Vector2(-1,0),new Vector2(999,999)));C(x.spawn.x==4.8f&&x.spawn.y==3&&x.resolver.ExplicitPoint==null&&x.resolver.Target==null&&x.resolver.Mode==SkillAimMode.Direction&&x.resolver.Direction.x==-1);});
 T("Target-real-helper-lock-unit-no-ground-spawn",()=>{var g=new GameObject();g.transform.position=new Vector3(9,3,0);var x=Helper.Fire(new ManualSkillAim(SkillAimMode.Target,Vector2.right,new Vector2(999,999),g.transform));C(x.spawn.x==5.2f&&x.resolver.Target==g&&x.resolver.ExplicitPoint.Value.x==9);});
 T("GroundPoint-real-helper-is-only-point-spawn",()=>{var x=Helper.Fire(new ManualSkillAim(SkillAimMode.GroundPoint,default,new Vector2(7,4)));C(x.spawn.x==7&&x.spawn.y==4&&x.resolver.Mode==SkillAimMode.GroundPoint);});
 T("Self-real-helper-ignores-mouse",()=>{var x=Helper.Fire(new ManualSkillAim(SkillAimMode.Self,new Vector2(-1,0),new Vector2(999,999)));C(x.spawn.x==5.2f&&x.spawn.y==3&&x.resolver.Target==null&&x.resolver.ExplicitPoint.Value.x==5);});
 T("legacy-NPC-point-path-still-relocates-to-point",()=>{var x=Helper.Fire(null,true);C(x.resolver.Mode==null&&x.spawn.x==99&&x.spawn.y==99);});
 T("existing-resolver-cone-filters-rear-side-dead-and-range",()=>{var caster=new GameObject().transform;var list=new List<Collider2D>();foreach(var p in new[]{new Vector3(-.1f,0,0),new Vector3(0,.2f,0),new Vector3(2,0,0),new Vector3(3,0,0),new Vector3(20,0,0)}){var g=new GameObject();g.transform.position=p;g.AddComponent<CharacterManager>();list.Add(g.AddComponent<Collider2D>());}list[2].GetComponent<CharacterManager>().IsTargetable=false;Physics2D.Candidates=list.ToArray();var r=new EquipmentSkillRuntimeData();r.sourceEquipment.CastSo.Range=5;r.resolvedRange=5;C(new TargetResolver().ResolveManualTarget(r,caster,Vector2.right)==list[3].transform);});
 T("cone-resolver-tie-break-and-no-target-fail-closed",()=>{var a=new GameObject();a.transform.position=new Vector3(2,0,0);a.AddComponent<CharacterManager>();var b=new GameObject();b.transform.position=a.transform.position;b.AddComponent<CharacterManager>();Physics2D.Candidates=new[]{b.AddComponent<Collider2D>(),a.AddComponent<Collider2D>()};var r=new EquipmentSkillRuntimeData();var resolver=new TargetResolver();C(resolver.ResolveManualTarget(r,new GameObject().transform,Vector2.right)==a.transform);Physics2D.Candidates=Array.Empty<Collider2D>();C(resolver.ResolveManualTarget(r,new GameObject().transform,Vector2.right)==null);});
 T("AimInputSource-legacy-mouse-and-unknown-fail-closed",()=>{C(SkillAimPolicy.ResolveInputSource(SkillAimPolicy.ParseInputSource(null))==AimInputSource.MouseDirection);C(SkillAimPolicy.ParseInputSource("bad")==AimInputSource.Invalid&&SkillAimPolicy.ResolveInputSource((AimInputSource)98)==AimInputSource.Invalid);});
 T("JSON-input-source-repeated-materialized-readback-and-unknown",()=>{var so=new EquipmentSkillSO();string json="{\"equipmentId\":\"x\",\"aimMode\":\"Direction\",\"aimInputSource\":\"KeyboardMoveDirection\"}";Generator.Materialize(json,so,new());Generator.Materialize(json,so,new());C(so.AimInputSource==AimInputSource.KeyboardMoveDirection);Generator.Materialize(json.Replace("KeyboardMoveDirection","unknown"),so,new());C(so.AimInputSource==AimInputSource.Invalid);Generator.Materialize("{\"equipmentId\":\"x\"}",so,new());C(so.AimInputSource==AimInputSource.MouseDirection);});
 T("Basic-G1-G3-cooldown-exact-one-materialized-readback",()=>{var rows=new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<List<Dictionary<string,object>>>(File.ReadAllText("Artifacts/Engineering/SeojinManualControl/rootfix-05/slot-manifest.json"));int n=0;foreach(var row in rows){if(!row.ContainsKey("castAsset"))continue;var json=new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<Dictionary<string,object>>(File.ReadAllText((string)row["json"]));var cast=(Dictionary<string,object>)json["cast"];float value=Convert.ToSingle(cast["cooldown"]);var so=new CastReadback();so.ApplyEditorData("basic",TargetingType.AutoTarget,0,value,1,false,null);so.ApplyEditorData("basic",TargetingType.AutoTarget,0,value,1,false,null);C(so.Cooldown==1.000f&&File.ReadAllText((string)row["castAsset"]).Contains("  cooldown: 1.000"));n++;}C(n==3);});
 Console.WriteLine($"PASS {count}/{count} production schema/materializer/helper/cone tests");
 }
}
