using System;using System.Collections.Generic;using System.Reflection;using Character.Control;using UnityEngine;
class ManualTests {
 static int count;static void Check(bool v,string m){if(!v)throw new Exception(m);}static void Test(string n,Action a){a();Console.WriteLine("PASS "+n);count++;}
 class Port:IManualGameplay{public bool Busy{get;set;}public bool ReadyNow=true;public int Calls,Clears;public int Slot;public AimSnapshot Aim;public ControlVector Dash,MoveValue;public Func<bool> Chain;public HashSet<int> Missing=new();public bool Available(int slot)=>!Missing.Contains(slot);public bool Ready(int slot)=>ReadyNow&&Available(slot);public bool Fire(int s,AimSnapshot a,ControlVector d,Func<bool> c){Calls++;Slot=s;Aim=a;Dash=d;Chain=c;Busy=true;return true;}public void Move(ControlVector d){MoveValue=d;}public void Clear(bool interrupt){Clears++;if(interrupt)Busy=false;}}
 static ManualInputFrame Frame()=>new ManualInputFrame{Aim=new AimSnapshot(new ControlVector(20,1),0,-4,32,4)};
 static void Tick(ManualControlCore c,Port p,ManualInputFrame f,ControlReason r=ControlReason.Manual,bool block=false)=>c.Tick(f,r,block,new ControlVector(-1,0),p);
 static void Update(SeojinManualControl c)=>typeof(SeojinManualControl).GetMethod("Update",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(c,null);
 static void Life(SeojinManualControl c,string name)=>typeof(SeojinManualControl).GetMethod(name,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(c,null);
 static void ResetUi(){Input.Clear();Application.isFocused=true;Time.timeScale=1;UnityEngine.EventSystems.EventSystem.current=null;Battle.Morpg.BattleMorpgLiveRoute.Locked=false;Session.GameSession.Instance=new();Camera.main=new GameObject().AddComponent<Camera>();}
 static (SeojinManualControl control,Character.CharacterManager actor,PartyMovementMono move,Character.CharacterSkillManager skills,Character.CharacterStateManager ai,SkillBrainMono brain) Rig(){ResetUi();var g=new GameObject();var a=g.AddComponent<Character.CharacterManager>();var m=g.AddComponent<PartyMovementMono>();g.AddComponent<MovementMono>();var s=g.AddComponent<Character.CharacterSkillManager>();for(int i=0;i<5;i++)s.SkillPool.Runtimes[SeojinControlPolicy.Slots[i]]=new Skill.EquipmentSkillRuntimeData{Slot=i};var state=g.AddComponent<Character.CharacterStateManager>();var brain=g.AddComponent<SkillBrainMono>();brain.enabled=false;g.AddComponent<SkillExecutorMono>();SeojinManualControl.Bind(a);return(g.GetComponent<SeojinManualControl>(),a,m,s,state,brain);}
 static void Main(){
  Test("axes-all16-opposites-diagonal-normalized",()=>{for(int mask=0;mask<16;mask++){var f=Frame();f.Up=(mask&1)!=0;f.Down=(mask&2)!=0;f.Left=(mask&4)!=0;f.Right=(mask&8)!=0;var v=f.Axes;int x=(f.Right?1:0)-(f.Left?1:0),y=(f.Up?1:0)-(f.Down?1:0);Check(Math.Sign(v.X)==Math.Sign(x)&&Math.Sign(v.Y)==Math.Sign(y),"cancellation");Check(Math.Abs(v.X*v.X+v.Y*v.Y-((x==0&&y==0)?0:1))<1e-5,"speed");}});
  Test("aim-snapshot-clamps-and-rejects-nonfinite",()=>{var a=new AimSnapshot(new ControlVector(80,-9),0,-4,32,4);Check(a.Point.X==32&&a.Point.Y==-4,"bounds");Check(!new AimSnapshot(new ControlVector(float.NaN,1),0,0,3,3).Point.Valid,"nan");});
  Test("startup-manual-and-idle-is-never-auto",()=>{var c=new ManualControlCore();var p=new Port();for(int i=0;i<30;i++)Tick(c,p,Frame());Check(c.Reason==ControlReason.Manual&&!c.AllowsAuto&&p.Calls==0,"idle takeover");});
  Test("click-tap-keeps-atomic-step-and-stops-next-chain",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.AttackDown=true;f.AttackHeld=true;Tick(c,p,f);Check(p.Calls==1&&p.Chain(),"tap start");Tick(c,p,Frame());Check(p.Busy&&!p.Chain()&&p.Calls==1,"release interrupted step or chained");});
  Test("held-repeat-after-recovery-and-cooldown-without-dedup-error",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.AttackHeld=true;Tick(c,p,f);for(int i=0;i<50;i++)Tick(c,p,f);Check(p.Calls==1,"busy duplicates");p.Busy=false;p.ReadyNow=false;for(int i=0;i<50;i++)Tick(c,p,f);Check(p.Calls==1,"cooldown duplicates");p.ReadyNow=true;Tick(c,p,f);Check(p.Calls==2,"held no repeat");});
  Test("skills-pending-point-is-snapshot-latest-mouse-does-not-follow",()=>{var c=new ManualControlCore();var p=new Port{ReadyNow=false};Tick(c,p,Frame());var f=Frame();f.SlotDown=2;Tick(c,p,f);f=Frame();f.Aim=new AimSnapshot(new ControlVector(1,2),0,-4,32,4);Tick(c,p,f);p.ReadyNow=true;Tick(c,p,f);Check(p.Calls==1&&p.Slot==2&&p.Aim.Point.X==20,"snapshot changed");});
  Test("missing-slot-fails-closed-without-blocking-basic",()=>{var c=new ManualControlCore();var p=new Port();p.Missing.Add(2);Tick(c,p,Frame());var f=Frame();f.SlotDown=2;f.AttackHeld=true;Tick(c,p,f);Check(p.Calls==1&&p.Slot==0,"missing slot jams input");});
  Test("dash-mouse-opposite-WASD-wins",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.DashDown=true;f.Right=true;f.CasterPosition=new ControlVector(10,0);f.Aim=new AimSnapshot(new ControlVector(1,0),0,-4,32,4);Tick(c,p,f);Check(p.Slot==4&&p.Dash.X==-1&&p.Dash.Y==0,"WASD overrode mouse");});
  Test("dash-epsilon-invalid-aim-WASD-then-last-facing-fallback",()=>{var near=new AimSnapshot(new ControlVector(3.001f,2),0,-4,32,4);var d=ManualControlCore.DashDirection(near,new ControlVector(3,2),new ControlVector(1,1),new ControlVector(-1,0));Check(Math.Abs(d.X-.7071068f)<1e-5&&Math.Abs(d.Y-.7071068f)<1e-5,"epsilon fallback");var invalid=new AimSnapshot(new ControlVector(float.NaN,0),0,-4,32,4);d=ManualControlCore.DashDirection(invalid,default,default,new ControlVector(-1,0));Check(d.X==-1,"invalid aim facing");var c=new ManualControlCore();var p=new Port();c.Tick(Frame(),ControlReason.Manual,false,new ControlVector(0,1),p);c.Tick(Frame(),ControlReason.Manual,false,new ControlVector(0,1),p);var f=Frame();f.DashDown=true;f.Aim=invalid;c.Tick(f,ControlReason.Manual,false,default,p);Check(p.Dash.Y==1,"last valid facing lost");});
  Test("dash-clamped-keydown-snapshot-survives-mouse-caster-readiness-change",()=>{var c=new ManualControlCore();var p=new Port{ReadyNow=false};Tick(c,p,Frame());var f=Frame();f.DashDown=true;f.Left=true;f.CasterPosition=new ControlVector(31,4);f.Aim=new AimSnapshot(new ControlVector(999,999),0,-4,32,4);Tick(c,p,f);f=Frame();f.CasterPosition=new ControlVector(100,100);f.Aim=new AimSnapshot(new ControlVector(0,-4),0,-4,32,4);p.ReadyNow=true;Tick(c,p,f);Check(p.Dash.X==1&&p.Dash.Y==0&&p.Aim.Point.X==32&&p.Aim.Point.Y==4,"snapshot or clamp changed");});
  Test("basic-press-snapshot-waits-and-each-held-cycle-resamples",()=>{var c=new ManualControlCore();var p=new Port{ReadyNow=false};Tick(c,p,Frame());var f=Frame();f.AttackDown=true;f.AttackHeld=true;Tick(c,p,f);f.AttackDown=false;f.Aim=new AimSnapshot(new ControlVector(2,3),0,-4,32,4);p.ReadyNow=true;Tick(c,p,f);Check(p.Calls==1&&p.Aim.Point.X==20,"press aim lost during cooldown");Tick(c,p,f);Check(p.Calls==1&&p.Aim.Point.X==20,"active cycle aim changed");p.Busy=false;Tick(c,p,f);Check(p.Calls==2&&p.Aim.Point.X==2&&p.Aim.Point.Y==3,"next held cycle not resampled");});
  Test("all-forced-reasons-clear-and-manual-handback-no-ghost",()=>{foreach(var reason in new[]{ControlReason.Transition,ControlReason.Death,ControlReason.CrowdControl,ControlReason.Cutscene,ControlReason.ExplicitAuto}){var c=new ManualControlCore();var p=new Port{ReadyNow=false};Tick(c,p,Frame());var f=Frame();f.SlotDown=1;Tick(c,p,f);Tick(c,p,f,reason);Check(c.AllowsAuto==(reason==ControlReason.ExplicitAuto),"forced AI permission");p.ReadyNow=true;Tick(c,p,f);Check(p.Calls==0&&!p.MoveValue.Nonzero,"handback ghost");Tick(c,p,Frame());Check(p.Calls==0,"stale queued skill");}});
  Test("ui-pause-buffer-clear-and-physical-state-resampled-next-frame",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.AttackHeld=true;f.Right=true;Tick(c,p,f,ControlReason.Manual,true);Tick(c,p,f);Check(p.Calls==0,"handback held ghost");Tick(c,p,f);Check(p.Calls==1,"next physical held lost");});
  Test("runtime-default-manual-and-NPC-not-bound",()=>{var x=Rig();Check(x.move.Controlled&&!x.ai.enabled&&!x.brain.enabled,"baseline manual");var npc=new GameObject().AddComponent<Character.CharacterManager>();npc.RuntimeData.characterSO.CharacterType=Character.CharacterType.Npc;SeojinManualControl.Bind(npc);Check(npc.GetComponent<SeojinManualControl>()==null,"NPC changed");});
  Test("runtime-input-reader-shifts-and-slots-clamp",()=>{var x=Rig();Update(x.control);Input.Held.Add(KeyCode.W);Input.Held.Add(KeyCode.D);Input.Down.Add(KeyCode.LeftShift);Input.mousePosition=new Vector3(-40,-20,0);Update(x.control);Check(x.skills.Calls.Count==1&&x.skills.Calls[0].slot==4&&x.skills.Calls[0].point.x==0&&x.skills.Calls[0].point.y==-1,"reader shift");Input.Clear();Input.Down.Add(KeyCode.Alpha3);Input.mousePosition=new Vector3(99,99,0);Update(x.control);Check(x.skills.Calls[1].slot==3&&x.skills.Calls[1].point.x==32&&x.skills.Calls[1].point.y==4,"reader aim clamp");});
  Test("runtime-UI-focus-pause-end-intents-zero",()=>{var x=Rig();Update(x.control);Input.MouseHeld=true;Input.Held.Add(KeyCode.D);UnityEngine.EventSystems.EventSystem.current=new UnityEngine.EventSystems.EventSystem{Over=true};Update(x.control);Check(x.skills.Calls.Count==0&&x.move.Input.x==0,"UI intent");UnityEngine.EventSystems.EventSystem.current=null;Time.timeScale=0;Update(x.control);Check(x.skills.Calls.Count==0,"pause");Time.timeScale=1;Session.GameSession.Instance.BattleSession.BattleRuntime.isCompleted=true;Update(x.control);Check(x.skills.Calls.Count==0,"end");});
  Test("runtime-OnDisable-restores-captured-baselines-and-zero-movement",()=>{var x=Rig();Update(x.control);Input.Held.Add(KeyCode.D);Update(x.control);Check(x.move.Input.x==1,"move setup");x.control.enabled=false;Life(x.control,"OnDisable");Check(x.ai.enabled&&!x.brain.enabled&&!x.move.Controlled&&x.move.Input.x==0&&!SeojinManualControl.Bound(x.actor.gameObject),"baseline restore");});
  Test("runtime-reenable-idempotent-manual-first-frame-no-held-ghost",()=>{var x=Rig();Update(x.control);x.control.enabled=false;Life(x.control,"OnDisable");x.control.enabled=true;Life(x.control,"OnEnable");Life(x.control,"OnEnable");Input.MouseHeld=true;Update(x.control);Check(x.skills.Calls.Count==0&&!x.ai.enabled&&x.move.Controlled,"re-enable state");Update(x.control);Check(x.skills.Calls.Count==1,"physical handback");x.control.enabled=false;Life(x.control,"OnDisable");Check(x.ai.enabled&&!x.brain.enabled,"idempotence lost captured baseline");});
  Test("runtime-explicit-auto-only-forced-state-never-AI-authorized",()=>{var x=Rig();Update(x.control);x.control.SetAutoMode(true);Update(x.control);Check(x.ai.enabled&&x.control.AutoAuthorized&&!x.move.Controlled,"explicit auto");x.actor.IsStunned=true;Update(x.control);Check(!x.ai.enabled&&!x.control.AutoAuthorized&&!x.control.ManualAuthorized,"CC auto commands");x.control.enabled=false;Life(x.control,"OnDisable");Check(x.ai.enabled&&!x.control.AutoAuthorized,"cleanup forced guard");x.actor.IsStunned=false;Check(x.control.AutoAuthorized,"legacy handback stuck");});
  Test("runtime-reenable-clears-stale-auto-authorization-before-Update",()=>{var x=Rig();Update(x.control);x.control.SetAutoMode(true);Update(x.control);x.control.enabled=false;Life(x.control,"OnDisable");x.control.enabled=true;Life(x.control,"OnEnable");Check(!x.control.AutoAuthorized&&!x.control.ManualAuthorized&&!x.ai.enabled,"stale authorization before Update");});
  Test("runtime-slots-1-2-3-retain-clamped-point-contract",()=>{for(int i=0;i<3;i++){var x=Rig();Update(x.control);x.actor.transform.position=new Vector3(10,0,0);Input.Down.Add(SeojinControlPolicy.Skills[i]);Input.mousePosition=new Vector3(-100,100,0);Update(x.control);Check(x.skills.Calls.Count==1&&x.skills.Calls[0].slot==i+1&&x.skills.Calls[0].point.x==0&&x.skills.Calls[0].point.y==4,"slot mapping or point changed");}});
  Console.WriteLine("PASS "+count+"/"+count+" production input/core/control lifecycle tests");
 }
}
