using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// StatMono
/// Generic stat container for characters (player, party members, monsters).
///
/// Responsibilities:
/// - HP / Mana / Damage data
/// - Damage / Heal / Mana consumption
/// - Optional contact damage tick
/// - Optional debug HP HUD generation
/// - Optional damage popup generation
///
/// Notes:
/// - Health is the single source of truth here.
/// - HUD text is generated by this component directly.
/// - External systems can use either Hp or Health naming aliases.
/// </summary>
[DisallowMultipleComponent]
public class StatMono : MonoBehaviour
{
    [Header("Health")]
    [SerializeField] private float maxHp = 100f;
    [SerializeField] private float currentHp = 100f;

    [Header("Mana")]
    [SerializeField] private float maxMana = 50f;
    [SerializeField] private float currentMana = 50f;

    [Header("Combat")]
    [SerializeField] private float damage = 10f;

    [Header("Contact Damage (DoT)")]
    [SerializeField] private bool enableContactDamage = false;
    [Tooltip("Enemies in this mask will be counted for contact damage.")]
    [SerializeField] private LayerMask enemyMask = ~0;

    [Tooltip("Overlap radius used to count enemies touching this character.")]
    [SerializeField] private float contactRadius = 0.55f;

    [Tooltip("Damage applied per enemy per tick (final damage = overlapCount * damagePerEnemyPerTick).")]
    [SerializeField] private float damagePerEnemyPerTick = 1f;

    [Tooltip("Minimum time between damage ticks.")]
    [SerializeField] private float contactTickInterval = 0.35f;

    [Header("HUD (Debug)")]
    [SerializeField] private bool showHpHud = true;
    [SerializeField] private bool hideHudWhenFullHp = false;
    [SerializeField] private Vector3 hudOffset = new Vector3(0f, 0.9f, 0f);
    [SerializeField] private Vector2 hudBarSize = new Vector2(1.8f, 0.22f);
    [SerializeField] private Vector2 hudBarBackgroundSize = new Vector2(1.95f, 0.30f);
    [SerializeField] private Color hudHighColor = Color.green;
    [SerializeField] private Color hudMidColor = Color.yellow;
    [SerializeField] private Color hudLowColor = Color.red;
    [SerializeField] private Color hudBackgroundColor = new Color(0f, 0f, 0f, 0.75f);
    [SerializeField] private string hudSortingLayerName = "UI";
    [SerializeField] private int hudSortingOrder = 200;

    [Header("Damage Popup")]
    [SerializeField] private bool showDamagePopups = true;
    [SerializeField] private float damagePopupLife = 0.6f;
    [SerializeField] private float damagePopupRiseSpeed = 1.2f;
    [SerializeField] private int damagePopupFontSize = 58;
    [SerializeField] private float damagePopupCharacterSize = 0.075f;
    [SerializeField] private string damagePopupSortingLayerName = "UI";
    [SerializeField] private int damagePopupSortingOrder = 210;

    [Header("Debug")]
    [SerializeField] private bool debugLog = false;

    private float _contactTickTimer;

    // HUD
    private GameObject _hudRoot;
    private SpriteRenderer _hudBackgroundRenderer;
    private SpriteRenderer _hudFillRenderer;
    private bool _lastHudVisible;
    private float _lastHudRatio = -1f;
    private Color _lastHudColor = new Color(-1f, -1f, -1f, -1f);
    private static Sprite _sharedHudBarSprite;

    public float MaxHp => maxHp;
    public float CurrentHp => currentHp;

    // Health naming aliases for external systems that use Health terminology.
    public float MaxHealth => maxHp;
    public float CurrentHealth => currentHp;

    public float MaxMana => maxMana;
    public float CurrentMana => currentMana;

    public float Hp01 => maxHp > 0f ? currentHp / maxHp : 0f;
    public float Damage => damage;
    public bool IsDead => currentHp <= 0f;

    private void Reset()
    {
        maxHp = Mathf.Max(1f, maxHp);
        currentHp = Mathf.Clamp(currentHp, 0f, maxHp);
        maxMana = Mathf.Max(0f, maxMana);
        currentMana = Mathf.Clamp(currentMana, 0f, maxMana);
    }

    private void OnValidate()
    {
        maxHp = Mathf.Max(1f, maxHp);
        currentHp = Mathf.Clamp(currentHp, 0f, maxHp);
        maxMana = Mathf.Max(0f, maxMana);
        currentMana = Mathf.Clamp(currentMana, 0f, maxMana);
        contactRadius = Mathf.Max(0f, contactRadius);
        damagePerEnemyPerTick = Mathf.Max(0f, damagePerEnemyPerTick);
        contactTickInterval = Mathf.Max(0.01f, contactTickInterval);
    }

    private void Awake()
    {
        maxHp = Mathf.Max(1f, maxHp);
        currentHp = Mathf.Clamp(currentHp, 0f, maxHp);
        maxMana = Mathf.Max(0f, maxMana);
        currentMana = Mathf.Clamp(currentMana, 0f, maxMana);
        _contactTickTimer = Random.Range(0f, Mathf.Max(0.01f, contactTickInterval));

        EnsureHud();
        RefreshHud(force: true);
    }

    private void Update()
    {
        if (enableContactDamage)
            TickContactDamage();
    }

    private void LateUpdate()
    {
        if (_hudRoot != null)
            _hudRoot.transform.position = transform.position + hudOffset;

        RefreshHud();
    }

    public void TakeDamage(float amount)
    {
        if (IsDead)
            return;

        if (amount <= 0f)
            return;

        if (showDamagePopups)
            SpawnDamagePopup(amount);

        currentHp -= amount;
        currentHp = Mathf.Max(0f, currentHp);
        RefreshHud();

        if (debugLog)
            Debug.Log($"[StatMono] {name} took {amount} damage. HP={currentHp}/{maxHp}");

        if (currentHp <= 0f)
        {
            OnDeath();
        }
    }

    public void Heal(float amount)
    {
        if (IsDead)
            return;

        if (amount <= 0f)
            return;

        currentHp += amount;
        currentHp = Mathf.Min(maxHp, currentHp);
        RefreshHud();

        if (debugLog)
            Debug.Log($"[StatMono] {name} healed {amount}. HP={currentHp}/{maxHp}");
    }

    public void SetMaxHealth(float value, bool fillToFull = false)
    {
        maxHp = Mathf.Max(1f, value);
        currentHp = fillToFull ? maxHp : Mathf.Clamp(currentHp, 0f, maxHp);
        RefreshHud(force: true);
    }

    public void SetMaxHp(float value, bool fillToFull = false)
    {
        SetMaxHealth(value, fillToFull);
    }

    public bool ConsumeMana(float amount)
    {
        if (amount <= 0f)
            return true;

        if (currentMana < amount)
            return false;

        currentMana -= amount;

        if (debugLog)
            Debug.Log($"[StatMono] {name} used {amount} mana. Mana={currentMana}/{maxMana}");

        return true;
    }

    public void RestoreMana(float amount)
    {
        if (amount <= 0f)
            return;

        currentMana += amount;
        currentMana = Mathf.Min(maxMana, currentMana);
    }

    // -----------------
    // Contact Damage (DoT)
    // -----------------

    private void TickContactDamage()
    {
        if (!enableContactDamage)
            return;

        if (IsDead)
            return;

        _contactTickTimer -= Time.deltaTime;
        if (_contactTickTimer > 0f)
            return;

        _contactTickTimer = Mathf.Max(0.05f, contactTickInterval);

        int overlap = CountEnemiesInRadius(contactRadius);
        if (overlap <= 0)
            return;

        float raw = Mathf.Max(0f, overlap * Mathf.Max(0f, damagePerEnemyPerTick));
        if (raw <= 0f)
            return;

        TakeDamage(raw);

        if (debugLog)
            Debug.Log($"[StatMono] ContactDoT overlap={overlap} dmg={raw:0.##} HP={currentHp:0.##}/{maxHp:0.##}");
    }

    private int CountEnemiesInRadius(float radius)
    {
        var hits = Physics2D.OverlapCircleAll(transform.position, radius, enemyMask);
        if (hits == null || hits.Length == 0)
            return 0;

        HashSet<StatMono> uniqueTargets = new HashSet<StatMono>();

        for (int i = 0; i < hits.Length; i++)
        {
            var c = hits[i];
            if (c == null)
                continue;

            if (c.isTrigger)
                continue;

            if (c.transform == transform || c.transform.IsChildOf(transform))
                continue;

            StatMono otherStat = c.GetComponentInParent<StatMono>();
            if (otherStat == null)
                continue;

            if (otherStat == this)
                continue;

            uniqueTargets.Add(otherStat);
        }

        return uniqueTargets.Count;
    }

    // -----------------
    // HUD
    // -----------------

    private void EnsureHud()
    {
        if (!showHpHud)
            return;

        if (_hudRoot == null)
        {
            Transform existing = transform.Find("StatHud");
            if (existing != null)
                _hudRoot = existing.gameObject;
        }

        if (_hudRoot == null)
        {
            _hudRoot = new GameObject("StatHud");
            _hudRoot.transform.SetParent(transform, false);
        }

        _hudRoot.transform.localPosition = hudOffset;

        Transform backgroundTransform = _hudRoot.transform.Find("Background");
        Transform fillTransform = _hudRoot.transform.Find("Fill");

        if (backgroundTransform == null)
        {
            GameObject background = new GameObject("Background");
            background.transform.SetParent(_hudRoot.transform, false);
            backgroundTransform = background.transform;
        }

        if (fillTransform == null)
        {
            GameObject fill = new GameObject("Fill");
            fill.transform.SetParent(_hudRoot.transform, false);
            fillTransform = fill.transform;
        }

        if (_hudBackgroundRenderer == null)
            _hudBackgroundRenderer = backgroundTransform.GetComponent<SpriteRenderer>();
        if (_hudBackgroundRenderer == null)
            _hudBackgroundRenderer = backgroundTransform.gameObject.AddComponent<SpriteRenderer>();

        if (_hudFillRenderer == null)
            _hudFillRenderer = fillTransform.GetComponent<SpriteRenderer>();
        if (_hudFillRenderer == null)
            _hudFillRenderer = fillTransform.gameObject.AddComponent<SpriteRenderer>();

        Sprite sharedSprite = GetSharedHudBarSprite();
        _hudBackgroundRenderer.sprite = sharedSprite;
        _hudFillRenderer.sprite = sharedSprite;

        _hudBackgroundRenderer.sortingLayerName = hudSortingLayerName;
        _hudBackgroundRenderer.sortingOrder = hudSortingOrder;
        _hudFillRenderer.sortingLayerName = hudSortingLayerName;
        _hudFillRenderer.sortingOrder = hudSortingOrder + 1;

        _hudBackgroundRenderer.transform.localPosition = Vector3.zero;
        _hudFillRenderer.transform.localPosition = Vector3.zero;
    }

    private void RefreshHud(bool force = false)
    {
        if (!showHpHud)
        {
            if (_hudRoot != null)
                _hudRoot.SetActive(false);
            return;
        }

        EnsureHud();
        if (_hudRoot == null || _hudBackgroundRenderer == null || _hudFillRenderer == null)
            return;

        float ratio = Hp01;
        bool visible = !IsDead && (!hideHudWhenFullHp || ratio < 0.999f);

        if (force || _lastHudVisible != visible)
        {
            _hudRoot.SetActive(visible);
            _lastHudVisible = visible;
        }

        if (!visible)
            return;

        Color nextColor = EvaluateHudColor(ratio);

        if (force)
        {
            _hudBackgroundRenderer.transform.localScale = new Vector3(hudBarBackgroundSize.x, hudBarBackgroundSize.y, 1f);
            _hudBackgroundRenderer.color = hudBackgroundColor;
        }

        if (force || !Mathf.Approximately(_lastHudRatio, ratio))
        {
            float fillWidth = Mathf.Max(0.001f, hudBarSize.x * ratio);
            _hudFillRenderer.transform.localScale = new Vector3(fillWidth, hudBarSize.y, 1f);
            _hudFillRenderer.transform.localPosition = new Vector3(-(hudBarSize.x - fillWidth) * 0.5f, 0f, 0f);
            _lastHudRatio = ratio;
        }

        if (force || _lastHudColor != nextColor)
        {
            _hudFillRenderer.color = nextColor;
            _lastHudColor = nextColor;
        }
    }

    private Color EvaluateHudColor(float hp01)
    {
        if (hp01 < 0.25f)
            return hudLowColor;

        if (hp01 < 0.6f)
            return hudMidColor;

        return hudHighColor;
    }

    private static Sprite GetSharedHudBarSprite()
    {
        if (_sharedHudBarSprite != null)
            return _sharedHudBarSprite;

        Texture2D tex = new Texture2D(1, 1, TextureFormat.RGBA32, false)
        {
            filterMode = FilterMode.Point,
            wrapMode = TextureWrapMode.Clamp
        };
        tex.SetPixel(0, 0, Color.white);
        tex.Apply();

        _sharedHudBarSprite = Sprite.Create(tex, new Rect(0, 0, 1, 1), new Vector2(0.5f, 0.5f), 1f);
        return _sharedHudBarSprite;
    }

    private void SpawnDamagePopup(float dmg)
    {
        var go = new GameObject("DmgPopup");
        go.transform.position = transform.position + hudOffset + new Vector3(Random.Range(-0.15f, 0.15f), 0f, 0f);

        var tm = go.AddComponent<TextMesh>();
        tm.anchor = TextAnchor.MiddleCenter;
        tm.alignment = TextAlignment.Center;
        tm.fontSize = Mathf.Max(32, damagePopupFontSize);
        tm.characterSize = Mathf.Max(0.04f, damagePopupCharacterSize);
        tm.text = $"{dmg:0}";
        tm.color = new Color(1f, 0.9f, 0.2f, 1f);

        var mr = tm.GetComponent<MeshRenderer>();
        mr.sortingLayerName = damagePopupSortingLayerName;
        mr.sortingOrder = damagePopupSortingOrder;

        var pop = go.AddComponent<DamagePopupMono>();
        pop.Initialize(damagePopupLife, damagePopupRiseSpeed);
    }

    private class DamagePopupMono : MonoBehaviour
    {
        private float _life;
        private float _rise;
        private float _t;
        private TextMesh _tm;

        public void Initialize(float life, float riseSpeed)
        {
            _life = Mathf.Max(0.05f, life);
            _rise = Mathf.Max(0.1f, riseSpeed);
            _tm = GetComponent<TextMesh>();
        }

        private void Update()
        {
            _t += Time.deltaTime;
            float k = Mathf.Clamp01(_t / _life);

            transform.position += Vector3.up * (_rise * Time.deltaTime);

            if (_tm != null)
            {
                var c = _tm.color;
                c.a = Mathf.Lerp(1f, 0f, k);
                _tm.color = c;
            }

            if (_t >= _life)
                Destroy(gameObject);
        }
    }

#if UNITY_EDITOR
    private void OnDrawGizmosSelected()
    {
        if (!enableContactDamage)
            return;

        Gizmos.color = new Color(1f, 0.2f, 0.2f, 0.35f);
        Gizmos.DrawWireSphere(transform.position, contactRadius);
    }
#endif

    private void OnDeath()
    {
        RefreshHud(force: true);

        if (debugLog)
            Debug.Log($"[StatMono] {name} died");

        // Future hooks:
        // - Drop items
        // - Notify AI systems
        // - Play animation
        Destroy(gameObject);
    }
}
