class HoverTests{
 static int count;static void C(bool ok,string n){if(!ok)throw new Exception(n);count++;}static bool Near(float a,float b)=>Math.Abs(Mathf.DeltaAngle(a,b))<.001f;
 static void Main(){
 for(int i=0;i<8;i++)foreach(float offset in new[]{0f,27f}){
  var d=new Vector2((float)Math.Cos(i*Math.PI/4),(float)Math.Sin(i*Math.PI/4));
  var root=new GameObject("ProjectileEntity");var scaler=new GameObject("Scaler");scaler.transform.SetParent(root.transform,false);scaler.AddComponent<Collider2D>();var visual=new GameObject("Renderer Animator");visual.transform.SetParent(scaler.transform,false);var renderer=visual.AddComponent<SpriteRenderer>();visual.transform.localScale=new Vector3(2,2,2);
  var owner=new GameObject("caster");var target=new GameObject("misleading target");target.transform.position=new Vector3(100,0,0);
  var dto=new HoverProjectileMoveDto{applyDirectionRotation=true,rotationOffset=offset};var factory=new FactoryProbe();var data=factory.Clone(new ProjectileRuntimeData{orientManualPresentation=true,direction=d,moveRuntime=dto});
  C(data.orientManualPresentation,"actual Factory clone keeps manual mode");C(Near(factory.Rotation(data).angle,0),"actual Factory spawn root zero");
  var movement=new SkillProjectileHoverMovement();var controller=new SkillProjectileMoveController(movement);controller.Initialize(dto,new SkillProjectileMovementContext{owner=owner.transform,projectileTransform=root.transform,targetTransform=target.transform,authoritativeDirection=data.NormalizedDirection,hasAuthoritativeDirection=true,visualOnlyDirectionRotation=true});
  C(Near(Mathf.Atan2(controller.GetDirection().y,controller.GetDirection().x)*Mathf.Rad2Deg,i*45),"actual Hover prefers snapshot over target/right/position");
  var lease=new ProjectileDirectionPresentationLease();C(lease.Begin(visual.transform,root.transform,renderer,data.NormalizedDirection,dto.applyDirectionRotation,dto.rotationOffset),"production hierarchy wrapper admitted");var wrapper=visual.transform.parent;
  for(int frame=0;frame<3;frame++){visual.transform.localRotation=Quaternion.identity;target.transform.position=new Vector3(-99,33,0);controller.TickMovement(.02f);lease.Apply();C(Near(visual.transform.rotation.angle,i*45+offset)&&Near(wrapper.rotation.angle,i*45+offset),"clip root rotation write cannot erase wrapper; visible forward");C(Near(root.transform.rotation.angle,0)&&Near(scaler.transform.rotation.angle,0)&&Near(owner.transform.rotation.angle,0),"collider/caster/gameplay root unchanged");}
  renderer.flipX=true;lease.Restore();C(visual.transform.parent==scaler.transform&&visual.transform.GetSiblingIndex()==0&&Near(visual.transform.localRotation.angle,0)&&visual.transform.localScale.x==2&&!renderer.flipX,"pool exact parent pose flip restore");lease.Restore();C(!lease.Active,"disable/despawn idempotent");
  lease.Begin(visual.transform,root.transform,renderer,d,false,offset);C(Near(visual.transform.rotation.angle,0),"apply false ignores offset and stays zero");lease.Restore();
 }
 foreach(string kind in new[]{"Hover","Linear","Warp"})foreach(bool apply in new[]{false,true}){
  SkillMoveRuntimeDto dto=kind=="Hover"?(SkillMoveRuntimeDto)new HoverProjectileMoveDto():kind=="Linear"?(SkillMoveRuntimeDto)new LinearProjectileMoveDto{targetPosition=new Vector2(0,5)}:new WarpProjectileMoveDto();dto.applyDirectionRotation=apply;dto.rotationOffset=19;
  ISkillProjectileMovement movement=kind=="Hover"?(ISkillProjectileMovement)new SkillProjectileHoverMovement():kind=="Linear"?(ISkillProjectileMovement)new SkillProjectileLinearMovement():new SkillProjectileWarpMovement();var root=new GameObject("root");var owner=new GameObject("owner");var c=new SkillProjectileMoveController(movement);c.Initialize(dto,new SkillProjectileMovementContext{owner=owner.transform,projectileTransform=root.transform,authoritativeDirection=new Vector2(0,1),hasAuthoritativeDirection=true,visualOnlyDirectionRotation=true});c.TickMovement(.02f);C(Near(root.transform.rotation.angle,0),kind+" manual root never rotates regardless flag");
 }
 var legacyRoot=new GameObject("legacy");var legacyTarget=new GameObject("legacyTarget");legacyTarget.transform.position=new Vector3(0,10,0);var legacyOwner=new GameObject("legacyOwner");var legacy=new SkillProjectileMoveController(new SkillProjectileHoverMovement());legacy.Initialize(new HoverProjectileMoveDto{applyDirectionRotation=true,rotationOffset=13},new SkillProjectileMovementContext{owner=legacyOwner.transform,targetTransform=legacyTarget.transform,projectileTransform=legacyRoot.transform});C(Near(legacyRoot.transform.rotation.angle,103),"nonmanual Hover legacy direction and offset retained");legacy.ResetController();legacyRoot.transform.rotation=Quaternion.identity;legacy.TickMovement(.1f);C(Near(legacyRoot.transform.rotation.angle,0),"reset clears rotation policy");
 var f=new FactoryProbe();foreach(bool apply in new[]{false,true}){var warp=f.Warp(new WarpProjectileMoveDto{applyDirectionRotation=apply,rotationOffset=31});C(warp.applyDirectionRotation==apply&&warp.rotationOffset==31,"actual Warp clone preserves flag offset");}
 var unsafeRoot=new GameObject("physics");var lease2=new ProjectileDirectionPresentationLease();C(!lease2.Begin(unsafeRoot.transform,unsafeRoot.transform,null,Vector2.right,true,90),"never wrap gameplay root");var child=new GameObject("physicsChild");child.transform.SetParent(unsafeRoot.transform,false);child.AddComponent<Rigidbody2D>();C(!lease2.Begin(child.transform,unsafeRoot.transform,null,Vector2.right,true,90),"never wrap physics subtree");
 var pooledRoot=new GameObject("pool");var pooledVisual=new GameObject("animated");pooledVisual.transform.SetParent(pooledRoot.transform,false);var pooledRenderer=pooledVisual.AddComponent<SpriteRenderer>();pooledRenderer.flipY=true;pooledVisual.transform.localPosition=new Vector3(2,3,0);pooledVisual.transform.localRotation=Quaternion.Euler(0,0,7);var existing=new GameObject("__ProjectileDirectionRotation");existing.transform.SetParent(pooledRoot.transform,false);existing.transform.localPosition=new Vector3(4,5,0);existing.transform.localScale=new Vector3(3,2,1);existing.transform.localRotation=Quaternion.Euler(0,0,11);
 for(int cycle=0;cycle<3;cycle++){var pooled=new ProjectileDirectionPresentationLease();pooled.Begin(pooledVisual.transform,pooledRoot.transform,pooledRenderer,new Vector2(0,1),true,5);pooledVisual.transform.localRotation=Quaternion.Euler(0,0,-20);C(Near(existing.transform.rotation.angle,95),"animated child artistic rotation does not overwrite parent wrapper");pooledRenderer.flipY=false;pooled.Restore();C(pooledVisual.transform.parent==pooledRoot.transform&&pooledVisual.transform.localPosition.x==2&&Near(pooledVisual.transform.localRotation.angle,7)&&pooledRenderer.flipY,"exact original child pose flip across repeated pool cycles");C(existing.transform.localPosition.x==4&&existing.transform.localScale.x==3&&Near(existing.transform.localRotation.angle,11),"existing wrapper local pose restored exactly");}
 Console.WriteLine("PASS "+count+" actual factory/hover/controller/wrapper assertions");
 }
}
