
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Stage;
using UnityEditor;
using UnityEngine;

namespace ResourceTools.Stage
{
    /// <summary>
    /// Builds a single RoundNodeSO / StageNodeSO style asset from a story json file,
    /// and connects its popupEvent field to the start PopupEventSO generated by PopupEventBuilder.
    ///
    /// Intended external usage:
    ///     StageNodeBuilder.BuildFromJsonPath(jsonPath, stageNodeOutputFolder, popupEventOutputFolder);
    ///
    /// Design rule:
    /// - JSON may keep roundNodeId / stageNodeId / startNodeId / nextNodeId.
    /// - Generated stage node SO keeps only actual SO references where possible.
    /// - PopupEventSO generation is delegated to PopupEventBuilder.
    /// </summary>
    public static class StageNodeBuilder
    {
        private const string DefaultStageNodeOutputFolder = "Assets/Resources/stage_new/nodes";
        private const string DefaultPopupEventOutputFolder = "Assets/Resources/stage_new/popup_events";

        public sealed class BuildResult
        {
            public RoundNodeSO stageNode;
            public string stageNodeId;
            public string stageNodeAssetPath;
            public PopupEventBuilder.BuildResult popupEventBuildResult;
            public readonly List<string> warnings = new();
        }

        [Serializable]
        private sealed class StageNodeJsonRoot
        {
            public string stageNodeId;
            public string roundNodeId;
            public string nodeId;
            public string actId;
            public string episodeId;
            public string chapterId;
            public int actNumber;
            public int episodeNumber;
            public string titleKo;
            public string summary;
            public string nodeType;
            public string roundNodeType;
            public string startNodeId;
            public bool isRequired;
            public bool hiddenByDefault;
            public List<string> tags;
        }

        public static BuildResult BuildFromJsonPath(string jsonPath)
        {
            return BuildFromJsonPath(jsonPath, DefaultStageNodeOutputFolder, DefaultPopupEventOutputFolder);
        }

        public static BuildResult BuildFromJsonPath(string jsonPath, string stageNodeOutputFolder)
        {
            return BuildFromJsonPath(jsonPath, stageNodeOutputFolder, DefaultPopupEventOutputFolder);
        }

        public static BuildResult BuildFromJsonPath(
            string jsonPath,
            string stageNodeOutputFolder,
            string popupEventOutputFolder)
        {
            if (string.IsNullOrWhiteSpace(jsonPath))
            {
                throw new ArgumentException("jsonPath is null or empty.", nameof(jsonPath));
            }

            if (!File.Exists(jsonPath))
            {
                throw new FileNotFoundException($"Stage node json not found: {jsonPath}", jsonPath);
            }

            if (string.IsNullOrWhiteSpace(stageNodeOutputFolder))
            {
                stageNodeOutputFolder = DefaultStageNodeOutputFolder;
            }

            if (string.IsNullOrWhiteSpace(popupEventOutputFolder))
            {
                popupEventOutputFolder = DefaultPopupEventOutputFolder;
            }

            EnsureFolder(stageNodeOutputFolder);
            EnsureFolder(popupEventOutputFolder);

            var jsonText = File.ReadAllText(jsonPath);
            var root = JsonUtility.FromJson<StageNodeJsonRoot>(jsonText);
            if (root == null)
            {
                throw new InvalidDataException($"Failed to parse stage node json: {jsonPath}");
            }

            var result = new BuildResult();

            // 1) Build popup event node chain first.
            result.popupEventBuildResult = PopupEventBuilder.BuildFromJsonPath(jsonPath, popupEventOutputFolder);
            if (result.popupEventBuildResult != null)
            {
                result.warnings.AddRange(result.popupEventBuildResult.warnings);
            }

            // 2) Build the round node that points to PopupEventBuilder.StartEvent.

            var stageNodeId = ResolveStageNodeId(root);
            if (string.IsNullOrWhiteSpace(stageNodeId))
            {
                throw new InvalidDataException($"Stage node json has no stageNodeId/roundNodeId/nodeId/actId/episodeId: {jsonPath}");
            }

            var assetPath = GetAssetPath(stageNodeOutputFolder, stageNodeId);
            RoundNodeSO asset = AssetDatabase.LoadAssetAtPath<RoundNodeSO>(assetPath);
            if (asset == null)
            {
                asset = ScriptableObject.CreateInstance<RoundNodeSO>();
                AssetDatabase.CreateAsset(asset, assetPath);
            }

            asset.nodeId = stageNodeId;
            asset.nodeType = ResolveNodeType(root);
            asset.isRequired = root.isRequired;
            asset.hiddenByDefault = root.hiddenByDefault;
            asset.tags = root.tags ?? new List<string>();

            var startEvent = result.popupEventBuildResult?.StartEvent as PopupEventSO;
            if (startEvent != null)
            {
                asset.popupEvent = startEvent;

                Sprite mainImage = FindMainImageByStageNodeId(stageNodeId);
                if (mainImage != null)
                {
                    startEvent.mainImage = mainImage;
                    EditorUtility.SetDirty(startEvent);
                }
                else
                {
                    result.warnings.Add($"Main image not found. stageNodeId={stageNodeId}");
                }
            }
            else
            {
                result.warnings.Add($"PopupEventBuilder did not return a PopupEventSO start event. startNodeId={root.startNodeId}");
            }

            EditorUtility.SetDirty(asset);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            result.stageNode = asset;
            result.stageNodeId = stageNodeId;
            result.stageNodeAssetPath = assetPath;
            return result;
        }

        private static string ResolveStageNodeId(StageNodeJsonRoot root)
        {
            if (!string.IsNullOrWhiteSpace(root.stageNodeId))
            {
                return root.stageNodeId;
            }

            if (!string.IsNullOrWhiteSpace(root.roundNodeId))
            {
                return root.roundNodeId;
            }

            if (!string.IsNullOrWhiteSpace(root.nodeId))
            {
                return root.nodeId;
            }

            if (!string.IsNullOrWhiteSpace(root.actId))
            {
                return root.actId;
            }

            if (!string.IsNullOrWhiteSpace(root.episodeId))
            {
                return root.episodeId;
            }

            return null;
        }

        private static RoundNodeType ResolveNodeType(StageNodeJsonRoot root)
        {
            string value = !string.IsNullOrWhiteSpace(root.roundNodeType)
                ? root.roundNodeType
                : root.nodeType;

            if (string.IsNullOrWhiteSpace(value))
            {
                return RoundNodeType.Event;
            }

            if (Enum.TryParse(value, true, out RoundNodeType parsed))
            {
                return parsed;
            }

            Debug.LogWarning($"[StageNodeBuilder] Unknown roundNodeType={value}. Fallback to Event.");
            return RoundNodeType.Event;
        }

        private static Sprite FindMainImageByStageNodeId(string stageNodeId)
        {
            if (string.IsNullOrWhiteSpace(stageNodeId))
            {
                return null;
            }

            string[] guids = AssetDatabase.FindAssets($"{stageNodeId} t:Sprite");
            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                Sprite sprite = AssetDatabase.LoadAssetAtPath<Sprite>(path);
                if (sprite == null)
                {
                    continue;
                }

                if (sprite.name == stageNodeId)
                {
                    return sprite;
                }
            }

            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                Sprite sprite = AssetDatabase.LoadAssetAtPath<Sprite>(path);
                if (sprite != null)
                {
                    return sprite;
                }
            }

            return null;
        }

        private static string GetAssetPath(string outputFolder, string id)
        {
            var safeFileName = SanitizeFileName(id) + ".asset";
            return CombineAssetPath(outputFolder, safeFileName);
        }

        private static string SanitizeFileName(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return "stage_node";
            }

            var invalidChars = Path.GetInvalidFileNameChars();
            var chars = value.Select(ch => invalidChars.Contains(ch) ? '_' : ch).ToArray();
            return new string(chars).Replace(':', '_').Replace('/', '_').Replace('\\', '_');
        }

        private static string CombineAssetPath(string folder, string fileName)
        {
            return (folder.TrimEnd('/', '\\') + "/" + fileName).Replace('\\', '/');
        }

        private static void EnsureFolder(string folderPath)
        {
            folderPath = folderPath.Replace('\\', '/').TrimEnd('/');
            if (AssetDatabase.IsValidFolder(folderPath))
            {
                return;
            }

            var parts = folderPath.Split('/');
            if (parts.Length == 0 || parts[0] != "Assets")
            {
                throw new ArgumentException($"Unity asset folder must start with Assets: {folderPath}");
            }

            var current = "Assets";
            for (var i = 1; i < parts.Length; i++)
            {
                var next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(current, parts[i]);
                }

                current = next;
            }
        }
    }
}
