 static T HudField<T>(SeojinDualDirectionHud h,string n)=>(T)typeof(SeojinDualDirectionHud).GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(h);
 static void HudTick(SeojinDualDirectionHud h,string n="LateUpdate")=>typeof(SeojinDualDirectionHud).GetMethod(n,BindingFlags.Instance|BindingFlags.NonPublic).Invoke(h,null);
 static (SeojinManualControl control,Character.CharacterManager actor,Battle.Presentation.BattleCharacterAuraView aura,SeojinDualDirectionHud hud) HudRig(){var x=Rig();Update(x.control);var a=new GameObject("Aura").AddComponent<Battle.Presentation.BattleCharacterAuraView>();a.BackArcRenderer=a.gameObject.AddComponent<SpriteRenderer>();a.BackArcRenderer.sprite=new Sprite{rect=Rect.MinMaxRect(0,0,256,128)};x.actor.gameObject.AddComponent<Battle.Presentation.BattleCharacterAuraBinding>().AuraView=a;SeojinDualDirectionHud.Ensure(x.control,x.actor);return(x.control,x.actor,a,a.GetComponent<SeojinDualDirectionHud>());}
// CASES
 for(int dir=0;dir<8;dir++){int i=dir;Test("HUD actual pivot octant "+i,()=>{var x=HudRig();Input.mousePosition=new Vector3((float)Math.Cos(i*Math.PI/4)*9,(float)Math.Sin(i*Math.PI/4)*9,0);HudTick(x.hud);var r=HudField<SpriteRenderer>(x.hud,"red");var p=HudField<Transform>(x.hud,"redPivot");var plane=HudField<Transform>(x.hud,"ground").localScale;float visible=(float)Math.Atan2(Math.Sin(p.localRotation.angle/Mathf.Rad2Deg)*plane.y,Math.Cos(p.localRotation.angle/Mathf.Rad2Deg)*plane.x)*Mathf.Rad2Deg;Check(r.enabled&&Math.Abs(Math.Abs(visible-i*45)%360)<.001f,"visible red world direction");Check(x.actor.transform.localRotation.angle==0&&x.aura.transform.localRotation.angle==0,"root/aura rotated");});}
 foreach(string gate in new[]{"selection","UI","pause","CC","rooted","death","transition","auto","end","disabled"})Test("HUD immediate hide "+gate,()=>{var x=HudRig();Input.mousePosition=new Vector3(9,0,0);Input.Held.Add(KeyCode.W);HudTick(x.hud);if(gate=="selection")x.aura.SetSelectionActive(false);if(gate=="UI")Application.isFocused=false;if(gate=="pause")Time.timeScale=0;if(gate=="CC")x.actor.IsStunned=true;if(gate=="rooted")x.actor.IsRooted=true;if(gate=="death")x.actor.RuntimeData.isDead=true;if(gate=="transition")Battle.Morpg.BattleMorpgLiveRoute.Locked=true;if(gate=="auto")x.control.SetAutoMode(true);if(gate=="end")Session.GameSession.Instance.BattleSession.BattleRuntime.isCompleted=true;if(gate=="disabled")x.control.enabled=false;HudTick(x.hud);Check(!HudField<SpriteRenderer>(x.hud,"red").enabled&&!HudField<SpriteRenderer>(x.hud,"blue").enabled,"gate leaked HUD");});
 Test("HUD simultaneous lanes live mouse and WASD",()=>{var x=HudRig();Input.mousePosition=new Vector3(9,0,0);Input.Held.Add(KeyCode.D);HudTick(x.hud);var r=HudField<SpriteRenderer>(x.hud,"red");var b=HudField<SpriteRenderer>(x.hud,"blue");Check(r.enabled&&b.enabled&&r.transform.localScale.x>b.transform.localScale.x,"overlapping same-direction lanes");Input.mousePosition=new Vector3(0,9,0);HudTick(x.hud);Check(HudField<Transform>(x.hud,"redPivot").localRotation.angle==90&&HudField<Transform>(x.hud,"bluePivot").localRotation.angle==0,"live mouse or independent blue wrong");});
 Test("HUD blue release and opposites hide without facing fallback",()=>{var x=HudRig();Input.Held.Add(KeyCode.W);HudTick(x.hud);Check(HudField<SpriteRenderer>(x.hud,"blue").enabled,"W hidden");Input.Held.Add(KeyCode.S);HudTick(x.hud);Check(!HudField<SpriteRenderer>(x.hud,"blue").enabled,"opposites shown");Input.Clear();HudTick(x.hud);Check(!HudField<SpriteRenderer>(x.hud,"blue").enabled,"release retained last movement");});
 Test("HUD invalid mouse hides red while valid WASD remains",()=>{var x=HudRig();Camera.main=null;Input.Held.Add(KeyCode.A);HudTick(x.hud);Check(!HudField<SpriteRenderer>(x.hud,"red").enabled&&HudField<SpriteRenderer>(x.hud,"blue").enabled,"invalid camera semantics");});
 Test("HUD repeated frame no resource load or hierarchy rebuild",()=>{var x=HudRig();Input.mousePosition=new Vector3(9,0,0);HudTick(x.hud);int loads=Resources.Loads;var pivot=HudField<Transform>(x.hud,"redPivot");for(int i=0;i<100;i++)HudTick(x.hud);Check(Resources.Loads==loads&&ReferenceEquals(pivot,HudField<Transform>(x.hud,"redPivot")),"per-frame load or allocation");SeojinDualDirectionHud.Ensure(x.control,x.actor);Check(ReferenceEquals(pivot,HudField<Transform>(x.hud,"redPivot")),"rebind duplicated hierarchy");HudTick(x.hud,"OnDisable");Check(!HudField<SpriteRenderer>(x.hud,"red").enabled&&HudField<Camera>(x.hud,"cachedCamera")==null,"pool disable state leak");});
 Test("HUD MORPG ground sorting and exact2 footprint",()=>{var x=HudRig();Battle.Morpg.MorpgEnvironmentRuntime.Active=new();Input.mousePosition=new Vector3(9,0,0);HudTick(x.hud);var r=HudField<SpriteRenderer>(x.hud,"red");var b=HudField<SpriteRenderer>(x.hud,"blue");Check(r.sortingOrder>Battle.BattlePresentationSortingPolicy.MorpgBackProps&&r.sortingOrder<Battle.BattlePresentationSortingPolicy.MorpgBodyOrder(-9999)&&r.sortingOrder<Battle.BattlePresentationSortingPolicy.MorpgGroundTelegraph,"ground order");Check(Math.Abs(HudField<Transform>(x.hud,"ground").localScale.x-.24696f)<.00001f,"exact2 footprint");Check(Math.Abs(r.transform.localScale.x/b.transform.localScale.x-1.15f)<.00001f,"red blue radius ratio");Battle.Morpg.MorpgEnvironmentRuntime.Active=null;});

 Test("HUD standard ground band background below telegraph",()=>{Check(Battle.BattlePresentationSortingPolicy.Background<Battle.BattlePresentationSortingPolicy.GroundDirectionHud&&Battle.BattlePresentationSortingPolicy.GroundDirectionHud<Battle.BattlePresentationSortingPolicy.GroundTelegraph,"non MORPG floor tie");});

 Test("HUD pointer-over-UI hides both per owner no-intent policy",()=>{var x=HudRig();Input.mousePosition=new Vector3(9,0,0);Input.Held.Add(KeyCode.W);UnityEngine.EventSystems.EventSystem.current=new UnityEngine.EventSystems.EventSystem{Over=true};HudTick(x.hud);Check(!HudField<SpriteRenderer>(x.hud,"red").enabled&&!HudField<SpriteRenderer>(x.hud,"blue").enabled,"pointer UI leaked intent");});
 Test("HUD aura render visibility suppresses hidden marker",()=>{var x=HudRig();Input.mousePosition=new Vector3(9,0,0);Input.Held.Add(KeyCode.W);x.aura.BackArcRenderer.enabled=false;HudTick(x.hud);Check(!HudField<SpriteRenderer>(x.hud,"red").enabled&&!HudField<SpriteRenderer>(x.hud,"blue").enabled,"invisible aura leaked HUD");});
 Test("HUD missing sprites stay hidden no retry allocations and rebind recovers",()=>{typeof(SeojinDualDirectionHud).GetField("redSprite",BindingFlags.Static|BindingFlags.NonPublic).SetValue(null,null);typeof(SeojinDualDirectionHud).GetField("blueSprite",BindingFlags.Static|BindingFlags.NonPublic).SetValue(null,null);Resources.Missing=true;var x=HudRig();Input.mousePosition=new Vector3(9,0,0);Input.Held.Add(KeyCode.W);var pivot=HudField<Transform>(x.hud,"redPivot");int loads=Resources.Loads;for(int i=0;i<50;i++)HudTick(x.hud);Check(!HudField<SpriteRenderer>(x.hud,"red").enabled&&!HudField<SpriteRenderer>(x.hud,"blue").enabled&&Resources.Loads==loads&&ReferenceEquals(pivot,HudField<Transform>(x.hud,"redPivot")),"missing sprite allocated/retried/shown");Resources.Missing=false;SeojinDualDirectionHud.Ensure(x.control,x.actor);HudTick(x.hud);Check(HudField<SpriteRenderer>(x.hud,"red").enabled&&HudField<SpriteRenderer>(x.hud,"blue").enabled&&ReferenceEquals(pivot,HudField<Transform>(x.hud,"redPivot")),"rebind could not recover same children");});
