using System;using System.Collections.Generic;using System.Reflection;using Character.Control;using UnityEngine;
class ManualTests {
 static int count;static void Check(bool v,string m){if(!v)throw new Exception(m);}static void Test(string n,Action a){a();Console.WriteLine("PASS "+n);count++;}
 class Port:IManualGameplay{public AimSnapshot Capture(int slot,AimSnapshot aim)=>aim;public bool Busy{get;set;}public bool ReadyNow=true;public int Calls,Clears,Attempts;public HashSet<int> Blocked=new(),Fail=new();public int Slot;public AimSnapshot Aim;public ControlVector Dash,MoveValue;public Func<bool> Chain;public HashSet<int> Missing=new();public bool Available(int slot)=>!Missing.Contains(slot);public bool Ready(int slot)=>ReadyNow&&Available(slot)&&!Blocked.Contains(slot);public bool Fire(int s,AimSnapshot a,ControlVector d,Func<bool> c){Attempts++;if(Fail.Contains(s))return false;Calls++;Slot=s;Aim=a;Dash=d;Chain=c;Busy=true;return true;}public void Move(ControlVector d){MoveValue=d;}public void Clear(bool interrupt){Clears++;if(interrupt)Busy=false;}}
 static ManualInputFrame Frame()=>new ManualInputFrame{Aim=new AimSnapshot(new ControlVector(20,1),0,-4,32,4)};
 static void Tick(ManualControlCore c,Port p,ManualInputFrame f,ControlReason r=ControlReason.Manual,bool block=false)=>c.Tick(f,r,block,new ControlVector(-1,0),p);
 static void Update(SeojinManualControl c)=>typeof(SeojinManualControl).GetMethod("Update",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(c,null);
 static void Life(SeojinManualControl c,string name)=>typeof(SeojinManualControl).GetMethod(name,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(c,null);
 static void ResetUi(){Input.Clear();Application.isFocused=true;Time.timeScale=1;UnityEngine.EventSystems.EventSystem.current=null;Battle.Morpg.BattleMorpgLiveRoute.Locked=false;Session.GameSession.Instance=new();Camera.main=new GameObject().AddComponent<Camera>();}
 static (SeojinManualControl control,Character.CharacterManager actor,PartyMovementMono move,Character.CharacterSkillManager skills,Character.CharacterStateManager ai,SkillBrainMono brain) Rig(){ResetUi();var g=new GameObject();var a=g.AddComponent<Character.CharacterManager>();var m=g.AddComponent<PartyMovementMono>();g.AddComponent<MovementMono>();var s=g.AddComponent<Character.CharacterSkillManager>();for(int i=0;i<5;i++)s.SkillPool.Runtimes[SeojinControlPolicy.Slots[i]]=new Skill.EquipmentSkillRuntimeData{Slot=i};s.SkillPool.Runtimes[SeojinControlPolicy.Slots[0]].sourceEquipment.AimMode=Skill.SkillAimMode.Direction;s.SkillPool.Runtimes[SeojinControlPolicy.Slots[4]].sourceEquipment.AimMode=Skill.SkillAimMode.Direction;s.SkillPool.Runtimes[SeojinControlPolicy.Slots[4]].sourceEquipment.AimInputSource=Skill.AimInputSource.KeyboardMoveDirection;var state=g.AddComponent<Character.CharacterStateManager>();var brain=g.AddComponent<SkillBrainMono>();brain.enabled=false;g.AddComponent<SkillExecutorMono>();SeojinManualControl.Bind(a);return(g.GetComponent<SeojinManualControl>(),a,m,s,state,brain);}
 static void Main(){
  Test("axes-all16-opposites-diagonal-normalized",()=>{for(int mask=0;mask<16;mask++){var f=Frame();f.Up=(mask&1)!=0;f.Down=(mask&2)!=0;f.Left=(mask&4)!=0;f.Right=(mask&8)!=0;var v=f.Axes;int x=(f.Right?1:0)-(f.Left?1:0),y=(f.Up?1:0)-(f.Down?1:0);Check(Math.Sign(v.X)==Math.Sign(x)&&Math.Sign(v.Y)==Math.Sign(y),"cancellation");Check(Math.Abs(v.X*v.X+v.Y*v.Y-((x==0&&y==0)?0:1))<1e-5,"speed");}});
  Test("aim-snapshot-clamps-and-rejects-nonfinite",()=>{var a=new AimSnapshot(new ControlVector(80,-9),0,-4,32,4);Check(a.Point.X==32&&a.Point.Y==-4,"bounds");Check(!new AimSnapshot(new ControlVector(float.NaN,1),0,0,3,3).Point.Valid,"nan");});
  Test("startup-manual-and-idle-is-never-auto",()=>{var c=new ManualControlCore();var p=new Port();for(int i=0;i<30;i++)Tick(c,p,Frame());Check(c.Reason==ControlReason.Manual&&!c.AllowsAuto&&p.Calls==0,"idle takeover");});
  Test("click-tap-keeps-atomic-step-and-stops-next-chain",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.AttackDown=true;f.AttackHeld=true;Tick(c,p,f);Check(p.Calls==1&&p.Chain(),"tap start");Tick(c,p,Frame());Check(p.Busy&&!p.Chain()&&p.Calls==1,"release interrupted step or chained");});
  Test("held-repeat-after-recovery-and-cooldown-without-dedup-error",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.AttackHeld=true;Tick(c,p,f);for(int i=0;i<50;i++)Tick(c,p,f);Check(p.Calls==1,"busy duplicates");p.Busy=false;p.ReadyNow=false;for(int i=0;i<50;i++)Tick(c,p,f);Check(p.Calls==1,"cooldown duplicates");p.ReadyNow=true;Tick(c,p,f);Check(p.Calls==2,"held no repeat");});
  Test("skill-not-ready-is-rejected-without-late-fire",()=>{var c=new ManualControlCore();var p=new Port{ReadyNow=false};Tick(c,p,Frame());var f=Frame();f.SlotDown=2;Tick(c,p,f);p.ReadyNow=true;Tick(c,p,Frame());Check(p.Calls==0&&c.PendingSlot==0,"cooldown queued a skill");f=Frame();f.SlotDown=2;f.Aim=new AimSnapshot(new ControlVector(1,2),0,-4,32,4);Tick(c,p,f);Check(p.Calls==1&&p.Aim.Point.X==1,"fresh keydown snapshot");});
  Test("missing-slot-fails-closed-without-blocking-basic",()=>{var c=new ManualControlCore();var p=new Port();p.Missing.Add(2);Tick(c,p,Frame());var f=Frame();f.SlotDown=2;f.AttackHeld=true;Tick(c,p,f);Check(p.Calls==1&&p.Slot==0,"missing slot jams input");});
  Test("dash-keyboard-opposite-mouse-wins",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.DashDown=true;f.Right=true;f.CasterPosition=new ControlVector(10,0);f.Aim=new AimSnapshot(new ControlVector(1,0),0,-4,32,4);Tick(c,p,f);Check(p.Slot==4&&p.Dash.X==1&&p.Dash.Y==0,"mouse overrode WASD");});
  Test("dash-zero-keys-last-movement-current-facing-right-fallback",()=>{var d=ManualControlCore.KeyboardMoveDirection(new ControlVector(1,1),new ControlVector(-1,0),default);Check(Math.Abs(d.X-.7071068f)<1e-5&&Math.Abs(d.Y-.7071068f)<1e-5,"normalized WASD");d=ManualControlCore.KeyboardMoveDirection(default,new ControlVector(0,1),new ControlVector(-1,0));Check(d.Y==1,"last movement priority");d=ManualControlCore.KeyboardMoveDirection(default,default,new ControlVector(-1,0));Check(d.X==-1,"current facing");d=ManualControlCore.KeyboardMoveDirection(default,default,default);Check(d.X==1,"right fallback");});
  Test("dash-not-ready-keydown-has-no-deferred-execution",()=>{var c=new ManualControlCore();var p=new Port{ReadyNow=false};Tick(c,p,Frame());var f=Frame();f.DashDown=true;f.Left=true;Tick(c,p,f);p.ReadyNow=true;Tick(c,p,Frame());Check(p.Calls==0&&c.PendingSlot==0,"dash late fire");});
  Test("basic-press-snapshot-waits-and-each-held-cycle-resamples",()=>{var c=new ManualControlCore();var p=new Port{ReadyNow=false};Tick(c,p,Frame());var f=Frame();f.AttackDown=true;f.AttackHeld=true;Tick(c,p,f);f.AttackDown=false;f.Aim=new AimSnapshot(new ControlVector(2,3),0,-4,32,4);p.ReadyNow=true;Tick(c,p,f);Check(p.Calls==1&&p.Aim.Point.X==20,"press aim lost during cooldown");Tick(c,p,f);Check(p.Calls==1&&p.Aim.Point.X==20,"active cycle aim changed");p.Busy=false;Tick(c,p,f);Check(p.Calls==2&&p.Aim.Point.X==2&&p.Aim.Point.Y==3,"next held cycle not resampled");});
  Test("all-forced-reasons-clear-and-manual-handback-no-ghost",()=>{foreach(var reason in new[]{ControlReason.Transition,ControlReason.Death,ControlReason.CrowdControl,ControlReason.Cutscene,ControlReason.ExplicitAuto}){var c=new ManualControlCore();var p=new Port{ReadyNow=false};Tick(c,p,Frame());var f=Frame();f.SlotDown=1;Tick(c,p,f);Tick(c,p,f,reason);Check(c.AllowsAuto==(reason==ControlReason.ExplicitAuto),"forced AI permission");p.ReadyNow=true;Tick(c,p,f);Check(p.Calls==0&&!p.MoveValue.Nonzero,"handback ghost");Tick(c,p,Frame());Check(p.Calls==0,"stale queued skill");}});
  Test("ui-pause-buffer-clear-and-physical-state-resampled-next-frame",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.AttackHeld=true;f.Right=true;Tick(c,p,f,ControlReason.Manual,true);Tick(c,p,f);Check(p.Calls==0,"handback held ghost");Tick(c,p,f);Check(p.Calls==1,"next physical held lost");});
  Test("runtime-default-manual-and-NPC-not-bound",()=>{var x=Rig();Check(x.move.Controlled&&!x.ai.enabled&&!x.brain.enabled,"baseline manual");var npc=new GameObject().AddComponent<Character.CharacterManager>();npc.RuntimeData.characterSO.CharacterType=Character.CharacterType.Npc;SeojinManualControl.Bind(npc);Check(npc.GetComponent<SeojinManualControl>()==null,"NPC changed");});
  Test("runtime-input-reader-space-dash-and-slots-clamp",()=>{var x=Rig();Update(x.control);Input.Held.Add(KeyCode.W);Input.Held.Add(KeyCode.D);Input.Down.Add(KeyCode.Space);Input.mousePosition=new Vector3(-40,-20,0);Update(x.control);Check(x.skills.Calls.Count==1&&x.skills.Calls[0].slot==4&&x.skills.Calls[0].point.x>0&&x.skills.Calls[0].point.y>0,"reader space dash");Input.Clear();Input.Down.Add(KeyCode.Alpha3);Input.mousePosition=new Vector3(99,99,0);Update(x.control);Check(x.skills.Calls[1].slot==3&&x.skills.Calls[1].point.x==32&&x.skills.Calls[1].point.y==4,"reader aim clamp");});
  Test("runtime-left-right-shift-charge-only",()=>{foreach(var key in new[]{KeyCode.LeftShift,KeyCode.RightShift}){var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimMode=Skill.SkillAimMode.Direction;x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimInputSource=Skill.AimInputSource.KeyboardMoveDirection;Update(x.control);Input.Held.Add(KeyCode.W);Input.Down.Add(key);Update(x.control);Check(x.skills.Calls.Count==1&&x.skills.Calls[0].slot==1&&x.skills.Aims[0].Direction.y==1,"shift did not fire Charge");}});
  Test("runtime-space-shift-same-frame-charge-priority-one-fire",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimMode=Skill.SkillAimMode.Direction;x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimInputSource=Skill.AimInputSource.KeyboardMoveDirection;Update(x.control);Input.Held.Add(KeyCode.D);Input.Down.Add(KeyCode.Space);Input.Down.Add(KeyCode.LeftShift);Update(x.control);Check(x.skills.Calls.Count==1&&x.skills.Calls[0].slot==1&&x.skills.Aims.Count==1,"simultaneous shortcuts duplicated or Dash won");});
  Test("runtime-shift-charge-cooldown-reject-is-nonconsuming",()=>{var x=Rig();Update(x.control);x.skills.Blocked.Add(1);Input.Held.Add(KeyCode.D);Input.Down.Add(KeyCode.RightShift);Update(x.control);Check(x.skills.Calls.Count==0&&x.skills.Aims.Count==0&&x.control.ManualAuthorized,"rejected Charge consumed or queued");Input.Clear();x.skills.Blocked.Clear();Update(x.control);Check(x.skills.Calls.Count==0,"rejected Charge fired late");});
  Test("runtime-number-charge-reuses-identical-runtime",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimMode=Skill.SkillAimMode.Direction;x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimInputSource=Skill.AimInputSource.KeyboardMoveDirection;Update(x.control);Input.Held.Add(KeyCode.A);Input.Down.Add(KeyCode.Alpha1);Update(x.control);Check(x.skills.Calls.Count==1&&x.skills.Calls[0].slot==1&&x.skills.Aims[0].Direction.x==-1,"number Charge path changed");});
  Test("runtime-UI-focus-pause-end-intents-zero",()=>{var x=Rig();Update(x.control);Input.MouseHeld=true;Input.Held.Add(KeyCode.D);UnityEngine.EventSystems.EventSystem.current=new UnityEngine.EventSystems.EventSystem{Over=true};Update(x.control);Check(x.skills.Calls.Count==0&&x.move.Input.x==0,"UI intent");UnityEngine.EventSystems.EventSystem.current=null;Time.timeScale=0;Update(x.control);Check(x.skills.Calls.Count==0,"pause");Time.timeScale=1;Session.GameSession.Instance.BattleSession.BattleRuntime.isCompleted=true;Update(x.control);Check(x.skills.Calls.Count==0,"end");});
  Test("runtime-OnDisable-restores-captured-baselines-and-zero-movement",()=>{var x=Rig();Update(x.control);Input.Held.Add(KeyCode.D);Update(x.control);Check(x.move.Input.x==1,"move setup");x.control.enabled=false;Life(x.control,"OnDisable");Check(x.ai.enabled&&!x.brain.enabled&&!x.move.Controlled&&x.move.Input.x==0&&!SeojinManualControl.Bound(x.actor.gameObject),"baseline restore");});
  Test("runtime-reenable-idempotent-manual-first-frame-no-held-ghost",()=>{var x=Rig();Update(x.control);x.control.enabled=false;Life(x.control,"OnDisable");x.control.enabled=true;Life(x.control,"OnEnable");Life(x.control,"OnEnable");Input.MouseHeld=true;Update(x.control);Check(x.skills.Calls.Count==0&&!x.ai.enabled&&x.move.Controlled,"re-enable state");Update(x.control);Check(x.skills.Calls.Count==1,"physical handback");x.control.enabled=false;Life(x.control,"OnDisable");Check(x.ai.enabled&&!x.brain.enabled,"idempotence lost captured baseline");});
  Test("runtime-explicit-auto-only-forced-state-never-AI-authorized",()=>{var x=Rig();Update(x.control);x.control.SetAutoMode(true);Update(x.control);Check(x.ai.enabled&&x.control.AutoAuthorized&&!x.move.Controlled,"explicit auto");x.actor.IsStunned=true;Update(x.control);Check(!x.ai.enabled&&!x.control.AutoAuthorized&&!x.control.ManualAuthorized,"CC auto commands");x.control.enabled=false;Life(x.control,"OnDisable");Check(x.ai.enabled&&!x.control.AutoAuthorized,"cleanup forced guard");x.actor.IsStunned=false;Check(x.control.AutoAuthorized,"legacy handback stuck");});
  Test("runtime-reenable-clears-stale-auto-authorization-before-Update",()=>{var x=Rig();Update(x.control);x.control.SetAutoMode(true);Update(x.control);x.control.enabled=false;Life(x.control,"OnDisable");x.control.enabled=true;Life(x.control,"OnEnable");Check(!x.control.AutoAuthorized&&!x.control.ManualAuthorized&&!x.ai.enabled,"stale authorization before Update");});
  Test("runtime-slots-1-2-3-retain-clamped-point-contract",()=>{for(int i=0;i<3;i++){var x=Rig();Update(x.control);x.actor.transform.position=new Vector3(10,0,0);Input.Down.Add(SeojinControlPolicy.Skills[i]);Input.mousePosition=new Vector3(-100,100,0);Update(x.control);Check(x.skills.Calls.Count==1&&x.skills.Calls[0].slot==i+1&&x.skills.Calls[0].point.x==0&&x.skills.Calls[0].point.y==4,"slot mapping or point changed");}});
  Test("Direction-raw-ray-is-independent-of-ground-bounds",()=>{var raw=new AimSnapshot(new ControlVector(100,1),0,-4,32,4).AtOrigin(new ControlVector(10,0));Check(raw.Direction.X>.999f&&raw.Direction.Y<.012f&&raw.Point.X==32,"direction used clamped point");});
  Test("GroundPoint-bounds-and-range-clamp-only",()=>{var x=new AimSnapshot(new ControlVector(100,100),0,-4,32,4).AtOrigin(new ControlVector(10,0));var p=x.GroundPoint(2);Check(Math.Abs((p.X-10)*(p.X-10)+p.Y*p.Y-4)<.0001f&&p.X<=32&&p.Y<=4,"ground clamp");});
  Test("runtime-Self-ignores-invalid-mouse-camera",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[2]].sourceEquipment.AimMode=Skill.SkillAimMode.Self;Update(x.control);Camera.main=null;Input.Down.Add(KeyCode.Alpha2);Update(x.control);Check(x.skills.Calls.Count==1&&x.skills.Aims[0].Mode==Skill.SkillAimMode.Self,"self demanded mouse");});
  Test("runtime-unknown-mode-has-no-fire",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimMode=Skill.SkillAimMode.Invalid;Update(x.control);Input.Down.Add(KeyCode.Alpha1);Update(x.control);Check(x.skills.Calls.Count==0,"unknown mode fired");});
  Test("runtime-Target-busy-input-is-rejected-before-lock",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimMode=Skill.SkillAimMode.Target;x.skills.LockedTarget=new GameObject().transform;Update(x.control);x.skills.ManualBusy=true;Input.Down.Add(KeyCode.Alpha1);Input.mousePosition=new Vector3(8,0,0);Update(x.control);Input.Clear();x.skills.ManualBusy=false;Update(x.control);Check(x.skills.Aims.Count==0&&x.skills.TargetLookups==0,"busy target queued/locked");});
  Test("runtime-Target-no-unit-is-fail-closed",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimMode=Skill.SkillAimMode.Target;Update(x.control);Input.Down.Add(KeyCode.Alpha1);Input.mousePosition=new Vector3(8,0,0);Update(x.control);Check(x.skills.Calls.Count==0,"target converted to point");});
  Test("runtime-slot-Direction-dispatches-direction-not-position",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[3]].sourceEquipment.AimMode=Skill.SkillAimMode.Direction;Update(x.control);Input.Down.Add(KeyCode.Alpha3);Input.mousePosition=new Vector3(-100,0,0);Update(x.control);Check(x.skills.Aims[0].Mode==Skill.SkillAimMode.Direction&&x.skills.Aims[0].Direction.x==-1&&x.skills.Aims[0].Point.x==0,"slot mode ignored");});
  Test("runtime-invalid-Direction-does-not-become-ground-shot",()=>{var x=Rig();Update(x.control);Camera.main=null;Input.MouseHeld=true;Update(x.control);Check(x.skills.Calls.Count==0,"invalid ray fired basic");});
  Test("runtime-SwiftStep-space-no-camera-uses-keyboard-and-retains-last-move",()=>{var x=Rig();Update(x.control);Camera.main=null;Input.Held.Add(KeyCode.A);Update(x.control);Input.Clear();Input.Down.Add(KeyCode.Space);Update(x.control);Check(x.skills.Aims.Count==1&&x.skills.Aims[0].Direction.x==-1,"mouse or facing overrode last movement");});
  Test("runtime-Charge-Keyboard-opposite-mouse-no-lock",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimMode=Skill.SkillAimMode.Direction;x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimInputSource=Skill.AimInputSource.KeyboardMoveDirection;Update(x.control);Input.Held.Add(KeyCode.D);Input.Down.Add(KeyCode.Alpha1);Input.mousePosition=new Vector3(-99,0,0);Update(x.control);Check(x.skills.Aims.Count==1&&x.skills.Aims[0].Direction.x==1&&x.skills.Aims[0].Target==null&&x.skills.Aims[0].Point.x==0&&x.skills.TargetLookups==0,"charge lock/point/keyboard override");});
  Test("runtime-unknown-input-source-fails-closed",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[4]].sourceEquipment.AimInputSource=Skill.AimInputSource.Invalid;Update(x.control);Input.Down.Add(KeyCode.Space);Input.Held.Add(KeyCode.D);Update(x.control);Check(x.skills.Aims.Count==0,"unknown source fired");});
  Test("runtime-Charge-busy-keydown-has-no-late-execution",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimMode=Skill.SkillAimMode.Direction;x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimInputSource=Skill.AimInputSource.KeyboardMoveDirection;Update(x.control);x.skills.ManualBusy=true;Input.Down.Add(KeyCode.Alpha1);Input.Held.Add(KeyCode.W);Update(x.control);Input.Clear();x.skills.ManualBusy=false;Update(x.control);Check(x.skills.Aims.Count==0&&x.skills.TargetLookups==0,"busy charge queued");});
  Test("rootfix-cooldown-keydown-keeps-held-basic-current-chain",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.AttackHeld=true;Tick(c,p,f);int clears=p.Clears;p.Blocked.Add(1);f.SlotDown=1;for(int i=0;i<50;i++)Tick(c,p,f);Check(p.Calls==1&&p.Chain()&&c.AttackHeld&&c.PendingSlot==0&&p.Clears==clears,"current combo preempted");Console.WriteLine("TRACE cooldown-spam: busy=true held=true pending=0 calls=1 cancelDelta=0");});
  Test("rootfix-rejected-cooldown-skill-basic-fires-same-tick",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());p.Blocked.Add(1);var f=Frame();f.AttackHeld=true;f.SlotDown=1;Tick(c,p,f);Check(p.Calls==1&&p.Slot==0&&p.Attempts==1&&c.PendingSlot==0,"cooldown starved basic");});
  Test("rootfix-Fire-false-does-not-clear-basic-press-snapshot",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());p.Blocked.Add(0);var f=Frame();f.AttackHeld=true;Tick(c,p,f);p.Blocked.Clear();p.Fail.Add(1);f.SlotDown=1;f.Aim=new AimSnapshot(new ControlVector(1,2),0,-4,32,4);Tick(c,p,f);Check(p.Calls==1&&p.Slot==0&&p.Aim.Point.X==20&&p.Attempts==2&&c.PendingSlot==0,"failed skill cleared press aim or consumed");});
  Test("rootfix-spam-does-not-starve-basic-or-queue-charge-after-cooldown",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());p.Blocked.Add(1);var f=Frame();f.AttackHeld=true;f.SlotDown=1;Tick(c,p,f);p.Busy=false;p.Blocked.Add(0);for(int i=0;i<100;i++)Tick(c,p,f);Check(p.Calls==1,"basic cooldown duplicated");p.Blocked.Remove(0);Tick(c,p,f);Check(p.Calls==2&&p.Slot==0,"held basic did not resume");p.Blocked.Clear();p.Busy=false;Tick(c,p,Frame());Check(p.Calls==2&&c.PendingSlot==0,"late charge fired");});
  Test("rootfix-only-successful-ready-skill-has-priority",()=>{var c=new ManualControlCore();var p=new Port();Tick(c,p,Frame());var f=Frame();f.AttackHeld=true;f.SlotDown=1;Tick(c,p,f);Check(p.Calls==1&&p.Slot==1&&!c.AttackHeld,"ready skill priority");p.Busy=false;f.SlotDown=0;Tick(c,p,f);Check(p.Calls==2&&p.Slot==0,"held requires repress");});
  Test("rootfix-runtime-resource-readiness-reject-no-clear-or-motion-stop",()=>{var x=Rig();Update(x.control);x.skills.Blocked.Add(1);int cancels=x.skills.Clears,stops=x.actor.GetComponent<MovementMono>().Stops;Input.MouseHeld=true;Input.mousePosition=new Vector3(9,0,0);Input.Down.Add(KeyCode.Alpha1);Update(x.control);Check(x.skills.Aims.Count==1&&x.skills.Calls[0].slot==0&&x.skills.Clears==cancels&&x.actor.GetComponent<MovementMono>().Stops==stops,"readiness reject preempted");});
  Test("rootfix-invalid-skill-reject-basic-held-continues-next-tick",()=>{var x=Rig();Update(x.control);x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[1]].sourceEquipment.AimMode=Skill.SkillAimMode.Invalid;Input.MouseHeld=true;Input.mousePosition=new Vector3(9,0,0);Input.Down.Add(KeyCode.Alpha1);Update(x.control);Input.Down.Clear();Update(x.control);Check(x.skills.Aims.Count==2&&x.skills.Calls.TrueForAll(c=>c.slot==0),"invalid skill held starvation");});
  Test("combo-adapter-reads-current-mouse-each-step",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[0]].comboProfile=new Skill.Combo{Enabled=true};Update(x.control);Input.MouseHeld=true;Input.mousePosition=new Vector3(9,0,0);Update(x.control);var read=x.skills.StepAim;Check(read!=null&&x.skills.Aims[0].Direction.x==1,"initial source missing");Check(read().Direction.x==1,"initial commit reread input");Time.frameCount++;Input.mousePosition=new Vector3(-9,0,0);var b=read();Input.mousePosition=new Vector3(0,-9,0);var c=read();Check(b.Direction.x==-1&&b.Direction.y==0&&c.Direction.y==-1,"callback reused whole combo aim");Check(b.Direction.x==-1,"prior value mutated");});
  Test("combo-adapter-no-camera-WASD-and-exact-last-step-fallback",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[0]].comboProfile=new Skill.Combo{Enabled=true};Update(x.control);Input.MouseHeld=true;Camera.main=null;Input.Held.Add(KeyCode.W);Update(x.control);Check(x.skills.Aims[0].Direction.x==0&&x.skills.Aims[0].Direction.y==1,"initial invalid ray failed");Input.Held.Clear();var next=x.skills.StepAim();Check(next.Direction.x==0&&next.Direction.y==1,"fallback quantized exact up to diagonal");Input.Held.Add(KeyCode.A);next=x.skills.StepAim();Check(next.Direction.x==-1&&next.Direction.y==0,"current WASD did not override last facing");});
  Test("combo-adapter-cooldown-reject-keeps-existing-provider",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[0]].comboProfile=new Skill.Combo{Enabled=true};Update(x.control);Input.MouseHeld=true;Input.mousePosition=new Vector3(9,0,0);Update(x.control);var read=x.skills.StepAim;x.skills.ManualBusy=true;x.skills.Blocked.Add(1);Input.Down.Add(KeyCode.Alpha1);Input.mousePosition=new Vector3(-9,0,0);Update(x.control);Check(ReferenceEquals(read,x.skills.StepAim)&&(++Time.frameCount>0)&&read().Direction.x==-1,"rejection replaced or froze combo provider");});
  foreach(string block in new[]{"UI","pause","auto","transition","disabled"})Test("combo-provider-immediate-"+block+"-blocks-without-input-read",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[0]].comboProfile=new Skill.Combo{Enabled=true};Update(x.control);Input.MouseHeld=true;Input.mousePosition=new Vector3(9,0,0);Update(x.control);var camera=Camera.main;int reads=camera.RayReads;if(block=="UI")UnityEngine.EventSystems.EventSystem.current=new UnityEngine.EventSystems.EventSystem{Over=true};if(block=="pause")Time.timeScale=0;if(block=="auto")x.control.SetAutoMode(true);if(block=="transition")Battle.Morpg.BattleMorpgLiveRoute.Locked=true;if(block=="disabled")x.control.enabled=false;Check(!x.skills.StepAim().IsValid&&camera.RayReads==reads,"unauthorized provider sampled before Update");});
  Test("combo-initial-commit-reuses-one-sample",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[0]].comboProfile=new Skill.Combo{Enabled=true};Update(x.control);Input.MouseHeld=true;Input.mousePosition=new Vector3(9,0,0);Update(x.control);int reads=Camera.main.RayReads;Input.mousePosition=new Vector3(-9,0,0);Check(x.skills.StepAim().Direction.x==1&&Camera.main.RayReads==reads,"same commit sampled twice");Time.frameCount++;Check(x.skills.StepAim().Direction.x==-1&&Camera.main.RayReads==reads+1,"next step not sampled");});
  Test("combo-delayed-first-commit-resamples-current-frame",()=>{var x=Rig();x.skills.SkillPool.Runtimes[SeojinControlPolicy.Slots[0]].comboProfile=new Skill.Combo{Enabled=true};Update(x.control);Input.MouseHeld=true;Input.mousePosition=new Vector3(9,0,0);Update(x.control);Time.frameCount++;Input.mousePosition=new Vector3(-9,0,0);Check(x.skills.StepAim().Direction.x==-1,"delayed first start used stale aim");});
  Test("UI-suspension-cancels-active-generation-before-handback",()=>{var x=Rig();Update(x.control);int cancels=x.skills.Clears;UnityEngine.EventSystems.EventSystem.current=new UnityEngine.EventSystems.EventSystem{Over=true};Update(x.control);Check(x.skills.Clears==cancels+1,"UI only cleared held without canceling coroutine epoch");});
  Console.WriteLine("PASS "+count+"/"+count+" production input/core/control lifecycle tests");
 }
}
